name: sqflite_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.12
  sqflite: ^2.2.5
  animation_search_bar: ^0.0.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
